/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

repositories {
    maven("https://repo.papermc.io/repository/maven-public/")
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.1.1.build.+")
    compileOnly("com.github.hyperdefined:hyperlib:1.0.14:all")
}

description = "hypermotd-paper"
java.sourceCompatibility = JavaVersion.VERSION_25

val pluginVersion = version.toString()

tasks.processResources {
    filteringCharset = "UTF-8"

    val props = mapOf("version" to pluginVersion)
    inputs.properties(props)

    filesMatching("paper-plugin.yml") {
        expand(props)
    }
}
